### Assignment 4 [Numpy and Pandas] (05-03-2022 to 06-03-2022)

#### 1.	Create a 2D array and print the dim and shape

In [13]:
import numpy as np
import pandas as pd

In [3]:
array1 = np.array([[1, 2, 3,],[6, 5, 7,]])
array1

array([[1, 2, 3],
       [6, 5, 7]])

In [9]:
array1.ndim

2

In [10]:
array1.shape

(2, 3)

#### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [11]:
list1 = np.arange(20)
array1 = slice(10, 15, 1)
list1[array1]

array([10, 11, 12, 13, 14])

#### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [16]:
array2 = np.array([[1,2,3,4,5],[3,4,5,6,7],[3,4,5,6,7],[11,32,4,5,67],[45,56,76,54,68],[3,5,8,4,6],[4,64,14,13,45]])
array3 = np.array([[3,4,5,6,7],[4,5,6,7,8],[7,8,9,2,5],[3,6,7,9,2],[4,6,23,45,65],[34,56,47,56,34],[45,23,47,53,84]])

In [17]:
array2.shape
array3.shape

(7, 5)

In [21]:
Addision = np.add(array2,array3)
Subraction= np.subtract(array2,array3)
Multiplication=np.multiply(array2,array3)
Division= np.divide(array2,array3)

In [26]:
Addision

array([[  4,   6,   8,  10,  12],
       [  7,   9,  11,  13,  15],
       [ 10,  12,  14,   8,  12],
       [ 14,  38,  11,  14,  69],
       [ 49,  62,  99,  99, 133],
       [ 37,  61,  55,  60,  40],
       [ 49,  87,  61,  66, 129]])

In [24]:
Subraction

array([[ -2,  -2,  -2,  -2,  -2],
       [ -1,  -1,  -1,  -1,  -1],
       [ -4,  -4,  -4,   4,   2],
       [  8,  26,  -3,  -4,  65],
       [ 41,  50,  53,   9,   3],
       [-31, -51, -39, -52, -28],
       [-41,  41, -33, -40, -39]])

In [27]:
Multiplication

array([[   3,    8,   15,   24,   35],
       [  12,   20,   30,   42,   56],
       [  21,   32,   45,   12,   35],
       [  33,  192,   28,   45,  134],
       [ 180,  336, 1748, 2430, 4420],
       [ 102,  280,  376,  224,  204],
       [ 180, 1472,  658,  689, 3780]])

In [28]:
Division

array([[ 0.33333333,  0.5       ,  0.6       ,  0.66666667,  0.71428571],
       [ 0.75      ,  0.8       ,  0.83333333,  0.85714286,  0.875     ],
       [ 0.42857143,  0.5       ,  0.55555556,  3.        ,  1.4       ],
       [ 3.66666667,  5.33333333,  0.57142857,  0.55555556, 33.5       ],
       [11.25      ,  9.33333333,  3.30434783,  1.2       ,  1.04615385],
       [ 0.08823529,  0.08928571,  0.17021277,  0.07142857,  0.17647059],
       [ 0.08888889,  2.7826087 ,  0.29787234,  0.24528302,  0.53571429]])

#### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [31]:
array4 = np.array([[1, 2, 3, 4],[6, 5, 7,]])
array4

C:\Users\Laksh\AppData\Local\Temp/ipykernel_3616/849505029.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array4 = np.array([[1, 2, 3, 4],[6, 5, 7,]])


array([list([1, 2, 3, 4]), list([6, 5, 7])], dtype=object)

#### 5.	Create two arrays of any dimension and perform vstack and hstack

In [32]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7],
       [11, 32,  4,  5, 67],
       [45, 56, 76, 54, 68],
       [ 3,  5,  8,  4,  6],
       [ 4, 64, 14, 13, 45]])

In [33]:
array3

array([[ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9,  2,  5],
       [ 3,  6,  7,  9,  2],
       [ 4,  6, 23, 45, 65],
       [34, 56, 47, 56, 34],
       [45, 23, 47, 53, 84]])

In [35]:
np.vstack((array2,array3))

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7],
       [11, 32,  4,  5, 67],
       [45, 56, 76, 54, 68],
       [ 3,  5,  8,  4,  6],
       [ 4, 64, 14, 13, 45],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9,  2,  5],
       [ 3,  6,  7,  9,  2],
       [ 4,  6, 23, 45, 65],
       [34, 56, 47, 56, 34],
       [45, 23, 47, 53, 84]])

In [36]:
np.hstack((array2,array3))

array([[ 1,  2,  3,  4,  5,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  7,  8,  9,  2,  5],
       [11, 32,  4,  5, 67,  3,  6,  7,  9,  2],
       [45, 56, 76, 54, 68,  4,  6, 23, 45, 65],
       [ 3,  5,  8,  4,  6, 34, 56, 47, 56, 34],
       [ 4, 64, 14, 13, 45, 45, 23, 47, 53, 84]])

#### 6.	Append two arrays using axis = 0 and axis = 1

In [47]:
np.append(array2,([34,45,34,45,34],[34,45,34,6,7]),axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7],
       [11, 32,  4,  5, 67],
       [45, 56, 76, 54, 68],
       [ 3,  5,  8,  4,  6],
       [ 4, 64, 14, 13, 45],
       [34, 45, 34, 45, 34],
       [34, 45, 34,  6,  7]])

In [56]:
np.append(array2,([34,45],[34,56],[34,6],[7,5],[4,5],[5,6],[45,55]),axis=1)

array([[ 1,  2,  3,  4,  5, 34, 45],
       [ 3,  4,  5,  6,  7, 34, 56],
       [ 3,  4,  5,  6,  7, 34,  6],
       [11, 32,  4,  5, 67,  7,  5],
       [45, 56, 76, 54, 68,  4,  5],
       [ 3,  5,  8,  4,  6,  5,  6],
       [ 4, 64, 14, 13, 45, 45, 55]])

#### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [86]:
lis1=[[1,'Raj','M',65,54,'O',9453434344,'NaN'],[2,'Belly','F',43,55,'B',9645343232,'NaN'],[3,'Alan','M',35,56,'A',63587934578,'NaN'],[4,'Ryan','M',45,57,'AB',87465544564,'NaN']]

NameError: name 'NaN' is not defined

In [62]:
lis1

[[1, 'Raj', 'M', 65, 54, 'O', 9453434344, 'NaN'],
 [2, 'Belly', 'F', 43, 55, 'B', 9645343232, 'NaN'],
 [3, 'Alan', 'M', 35, 56, 'A', 63587934578, 'NaN'],
 [4, 'Ryan', 'M', 45, 57, 'AB', 87465544564, 'NaN']]

In [76]:
df1 = pd.DataFrame(lis1,columns=['S.No','Name','Gender','Age','Pat No','Blood group','phone No','Email address'])
df1

S.No   Name Gender  Age  Pat No Blood group     phone No Email address
0     1    Raj      M   65      54           O   9453434344           NaN
1     2  Belly      F   43      55           B   9645343232           NaN
2     3   Alan      M   35      56           A  63587934578           NaN
3     4   Ryan      M   45      57          AB  87465544564           NaN

#### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [64]:
d1 ={'age':[25,29,30,45,34,45,67,56], 'salery':[5000,6000,7000,4500,5000,6000,4500,5600], 'experience':[3,4,6,6,7,5,3,5],'Gender':['M','M','M','F','F','M','M','M']}

In [67]:
df2= pd.DataFrame(d1, index=[1,2,3,4,5,6,7,8])

In [68]:
df2

age  salery  experience Gender
1   25    5000           3      M
2   29    6000           4      M
3   30    7000           6      M
4   45    4500           6      F
5   34    5000           7      F
6   45    6000           5      M
7   67    4500           3      M
8   56    5600           5      M

#### loc and iloc to subset the data for the above dataframe

In [72]:
df2.loc[:6,['age','Gender']]

age Gender
1   25      M
2   29      M
3   30      M
4   45      F
5   34      F
6   45      M

In [75]:
df2.iloc[0:5,0:5]

age  salery  experience Gender
1   25    5000           3      M
2   29    6000           4      M
3   30    7000           6      M
4   45    4500           6      F
5   34    5000           7      F

#### 10.	How to check the total number of not null values in a column?

In [79]:
df1

S.No   Name Gender  Age  Pat No Blood group     phone No Email address
0     1    Raj      M   65      54           O   9453434344           NaN
1     2  Belly      F   43      55           B   9645343232           NaN
2     3   Alan      M   35      56           A  63587934578           NaN
3     4   Ryan      M   45      57          AB  87465544564           NaN

In [82]:
df1['Email address'].notnull().sum()

4

#### 11.	Create a dataframe with missing values and fill them all with 100 

In [107]:
df1 = pd.DataFrame(np.random.randn(5,3), index=['a','b','c','d','e',], columns =['One','Two','Three'])
df1

One       Two     Three
a  1.027623 -1.474203 -0.133919
b -0.446140  1.542498  1.334122
c  0.335096  1.158813  0.145849
d  0.741373 -1.658592  1.258188
e -1.546202  0.231974 -1.520969

In [108]:
df1= df1.reindex(['a','b','c','d','e','f'])
df1

One       Two     Three
a  1.027623 -1.474203 -0.133919
b -0.446140  1.542498  1.334122
c  0.335096  1.158813  0.145849
d  0.741373 -1.658592  1.258188
e -1.546202  0.231974 -1.520969
f       NaN       NaN       NaN

In [109]:
df1.fillna(100, inplace=True)
df1

One         Two       Three
a    1.027623   -1.474203   -0.133919
b   -0.446140    1.542498    1.334122
c    0.335096    1.158813    0.145849
d    0.741373   -1.658592    1.258188
e   -1.546202    0.231974   -1.520969
f  100.000000  100.000000  100.000000

#### 12.	Create a dataframe with missing values and drop the null records

In [110]:
df4 = pd.DataFrame(lis1,columns=['S.No','Name','Gender','Age','Pat No','Blood group','phone No','Email address'])
df4

S.No   Name Gender  Age  Pat No Blood group     phone No Email address
0     1    Raj      M   65      54           O   9453434344           NaN
1     2  Belly      F   43      55           B   9645343232           NaN
2     3   Alan      M   35      56           A  63587934578           NaN
3     4   Ryan      M   45      57          AB  87465544564           NaN

In [113]:
df4=df4.reindex([0,1,2,3,4])
df4

S.No   Name Gender   Age  Pat No Blood group      phone No Email address
0   1.0    Raj      M  65.0    54.0           O  9.453434e+09           NaN
1   2.0  Belly      F  43.0    55.0           B  9.645343e+09           NaN
2   3.0   Alan      M  35.0    56.0           A  6.358793e+10           NaN
3   4.0   Ryan      M  45.0    57.0          AB  8.746554e+10           NaN
4   NaN    NaN    NaN   NaN     NaN         NaN           NaN           NaN

In [114]:
df4.dropna()

S.No   Name Gender   Age  Pat No Blood group      phone No Email address
0   1.0    Raj      M  65.0    54.0           O  9.453434e+09           NaN
1   2.0  Belly      F  43.0    55.0           B  9.645343e+09           NaN
2   3.0   Alan      M  35.0    56.0           A  6.358793e+10           NaN
3   4.0   Ryan      M  45.0    57.0          AB  8.746554e+10           NaN

#### 13.	Perform following aggregation task on below table
a.	Get the average age group by Regrion
b.	Get the sum of Age and Validation group by Hair color and then reset the index
c.	Get the man and the median of Age group by Region


In [127]:
df5=pd.DataFrame([[48,'Black','SW',1],[22,'Black','SW',0],[27,'Brown','NE',0],[28,'Black','SE',3],[21,'Blond','SE',1], [51,'Black','NW',0], [23,'Brown','SE',1]],columns =['AGE','HAIR COLOR','US REGION','VALIDATION'])

In [120]:
df5

AGE HAIR COLOR US REGION  VALIDATION
0   48      Black        SW           1
1   22      Black        SW           0
2   27      Brown        NE           0
3   28      Black        SE           3
4   21      Blond        SE           1
5   51      Black        NW           0
6   23      Brown        SE           1

In [131]:
#a.	Get the average age group by Regrion
df5.groupby(['US REGION'])['AGE'].sum()

US REGION
NE    27
NW    51
SE    72
SW    70
Name: AGE, dtype: int64

In [133]:
df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum()

C:\Users\Laksh\AppData\Local\Temp/ipykernel_3616/1540162951.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum()


AGE  VALIDATION
HAIR COLOR                 
Black       149           4
Blond        21           1
Brown        50           1

In [134]:
# b.	Get the sum of Age and Validation group by Hair color and then reset the index
df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()

C:\Users\Laksh\AppData\Local\Temp/ipykernel_3616/3286254245.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df5.groupby(['HAIR COLOR'])['AGE','VALIDATION'].sum().reset_index()


HAIR COLOR  AGE  VALIDATION
0      Black  149           4
1      Blond   21           1
2      Brown   50           1

In [135]:
#c.	Get the man and the median of Age group by Region
df5.groupby(['US REGION'])['AGE'].agg([np.mean, np.median]).reset_index()

US REGION  mean  median
0        NE  27.0    27.0
1        NW  51.0    51.0
2        SE  24.0    23.0
3        SW  35.0    35.0

#### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [137]:
df6 = pd.DataFrame([[25,'Black','SW',1],
                        [30,'Black','NW',1],
                        [45,'Red','NE',1],
                        [35,'Blond','SW',0],
                        [33,'Brown','SW',0],
                        [35,'Brown','NE',0],
                        [25,'Black','SW',0],
                        [52,'Brown','SE',0],
                        [21,'Blond','SW',1],
                        [24,'Blond','NE',0],
                        [48,'Black','SW',1],
                        [22,'Black','SW',0],
                        [27,'Brown','NE',0],
                        [28,'Black','SE',1],
                        [21,'Blond','SE',1],
                        [51,'Black','NW',0],
                        [23,'Brown','SE',1],                        
                       ]
                       ,columns =['AGE','HAIR COLOR','US REGION','VALIDATION'])

In [138]:
df6

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [139]:
df7 = df6.iloc[:10]
df8 = df6.iloc[10:]

In [140]:
df7

AGE HAIR COLOR US REGION  VALIDATION
0   25      Black        SW           1
1   30      Black        NW           1
2   45        Red        NE           1
3   35      Blond        SW           0
4   33      Brown        SW           0
5   35      Brown        NE           0
6   25      Black        SW           0
7   52      Brown        SE           0
8   21      Blond        SW           1
9   24      Blond        NE           0

In [141]:
df8

AGE HAIR COLOR US REGION  VALIDATION
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [149]:
pd.merge(df7,df8, on='US REGION')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      25        Black        SW             1     48        Black   
1      25        Black        SW             1     22        Black   
2      35        Blond        SW             0     48        Black   
3      35        Blond        SW             0     22        Black   
4      33        Brown        SW             0     48        Black   
5      33        Brown        SW             0     22        Black   
6      25        Black        SW             0     48        Black   
7      25        Black        SW             0     22        Black   
8      21        Blond        SW             1     48        Black   
9      21        Blond        SW             1     22        Black   
10     30        Black        NW             1     51        Black   
11     45          Red        NE             1     27        Brown   
12     35        Brown        NE             0     27        Brown   
13     24        Blond        NE             0     27        Brown   
14     52        Brown        SE             0     28        Black   
15     52        Brown        SE             0     21        Blond   
16     52        Brown        SE             0     23        Brown   

    VALIDATION_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             1

In [147]:
df5.merge(df6, on='US REGION', how = 'left')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      48        Black        SW             1     25        Black   
1      48        Black        SW             1     35        Blond   
2      48        Black        SW             1     33        Brown   
3      48        Black        SW             1     25        Black   
4      48        Black        SW             1     21        Blond   
5      48        Black        SW             1     48        Black   
6      48        Black        SW             1     22        Black   
7      22        Black        SW             0     25        Black   
8      22        Black        SW             0     35        Blond   
9      22        Black        SW             0     33        Brown   
10     22        Black        SW             0     25        Black   
11     22        Black        SW             0     21        Blond   
12     22        Black        SW             0     48        Black   
13     22        Black        SW             0     22        Black   
14     27        Brown        NE             0     45          Red   
15     27        Brown        NE             0     35        Brown   
16     27        Brown        NE             0     24        Blond   
17     27        Brown        NE             0     27        Brown   
18     28        Black        SE             3     52        Brown   
19     28        Black        SE             3     28        Black   
20     28        Black        SE             3     21        Blond   
21     28        Black        SE             3     23        Brown   
22     21        Blond        SE             1     52        Brown   
23     21        Blond        SE             1     28        Black   
24     21        Blond        SE             1     21        Blond   
25     21        Blond        SE             1     23        Brown   
26     51        Black        NW             0     30        Black   
27     51        Black        NW             0     51        Black   
28     23        Brown        SE             1     52        Brown   
29     23        Brown        SE             1     28        Black   
30     23        Brown        SE             1     21        Blond   
31     23        Brown        SE             1     23        Brown   

    VALIDATION_y  
0              1  
1              0  
2              0  
3              0  
4              1  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             1  
13             0  
14             1  
15             0  
16             0  
17             0  
18             0  
19             1  
20             1  
21             1  
22             0  
23             1  
24             1  
25             1  
26             1  
27             0  
28             0  
29             1  
30             1  
31             1

In [150]:
df5.merge(df6, on='US REGION', how = 'right')

AGE_x HAIR COLOR_x US REGION  VALIDATION_x  AGE_y HAIR COLOR_y  \
0      48        Black        SW             1     25        Black   
1      22        Black        SW             0     25        Black   
2      51        Black        NW             0     30        Black   
3      27        Brown        NE             0     45          Red   
4      48        Black        SW             1     35        Blond   
5      22        Black        SW             0     35        Blond   
6      48        Black        SW             1     33        Brown   
7      22        Black        SW             0     33        Brown   
8      27        Brown        NE             0     35        Brown   
9      48        Black        SW             1     25        Black   
10     22        Black        SW             0     25        Black   
11     28        Black        SE             3     52        Brown   
12     21        Blond        SE             1     52        Brown   
13     23        Brown        SE             1     52        Brown   
14     48        Black        SW             1     21        Blond   
15     22        Black        SW             0     21        Blond   
16     27        Brown        NE             0     24        Blond   
17     48        Black        SW             1     48        Black   
18     22        Black        SW             0     48        Black   
19     48        Black        SW             1     22        Black   
20     22        Black        SW             0     22        Black   
21     27        Brown        NE             0     27        Brown   
22     28        Black        SE             3     28        Black   
23     21        Blond        SE             1     28        Black   
24     23        Brown        SE             1     28        Black   
25     28        Black        SE             3     21        Blond   
26     21        Blond        SE             1     21        Blond   
27     23        Brown        SE             1     21        Blond   
28     51        Black        NW             0     51        Black   
29     28        Black        SE             3     23        Brown   
30     21        Blond        SE             1     23        Brown   
31     23        Brown        SE             1     23        Brown   

    VALIDATION_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              0  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1  
18             1  
19             0  
20             0  
21             0  
22             1  
23             1  
24             1  
25             1  
26             1  
27             1  
28             0  
29             1  
30             1  
31             1

#### 15.	Split the below table and perform concat row wise and column wise

In [153]:
df6

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [154]:
df7

AGE HAIR COLOR US REGION  VALIDATION
0   25      Black        SW           1
1   30      Black        NW           1
2   45        Red        NE           1
3   35      Blond        SW           0
4   33      Brown        SW           0
5   35      Brown        NE           0
6   25      Black        SW           0
7   52      Brown        SE           0
8   21      Blond        SW           1
9   24      Blond        NE           0

In [155]:
df8

AGE HAIR COLOR US REGION  VALIDATION
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [156]:
pd.concat([df7, df8]) #Row wise operation

AGE HAIR COLOR US REGION  VALIDATION
0    25      Black        SW           1
1    30      Black        NW           1
2    45        Red        NE           1
3    35      Blond        SW           0
4    33      Brown        SW           0
5    35      Brown        NE           0
6    25      Black        SW           0
7    52      Brown        SE           0
8    21      Blond        SW           1
9    24      Blond        NE           0
10   48      Black        SW           1
11   22      Black        SW           0
12   27      Brown        NE           0
13   28      Black        SE           1
14   21      Blond        SE           1
15   51      Black        NW           0
16   23      Brown        SE           1

In [157]:
pd.concat([df7, df8],axis=1) #column wise operation

AGE HAIR COLOR US REGION  VALIDATION   AGE HAIR COLOR US REGION  \
0   25.0      Black        SW         1.0   NaN        NaN       NaN   
1   30.0      Black        NW         1.0   NaN        NaN       NaN   
2   45.0        Red        NE         1.0   NaN        NaN       NaN   
3   35.0      Blond        SW         0.0   NaN        NaN       NaN   
4   33.0      Brown        SW         0.0   NaN        NaN       NaN   
5   35.0      Brown        NE         0.0   NaN        NaN       NaN   
6   25.0      Black        SW         0.0   NaN        NaN       NaN   
7   52.0      Brown        SE         0.0   NaN        NaN       NaN   
8   21.0      Blond        SW         1.0   NaN        NaN       NaN   
9   24.0      Blond        NE         0.0   NaN        NaN       NaN   
10   NaN        NaN       NaN         NaN  48.0      Black        SW   
11   NaN        NaN       NaN         NaN  22.0      Black        SW   
12   NaN        NaN       NaN         NaN  27.0      Brown        NE   
13   NaN        NaN       NaN         NaN  28.0      Black        SE   
14   NaN        NaN       NaN         NaN  21.0      Blond        SE   
15   NaN        NaN       NaN         NaN  51.0      Black        NW   
16   NaN        NaN       NaN         NaN  23.0      Brown        SE   

    VALIDATION  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0